---
abstract: ~
author:
  - 'Idea by Tony Bowden and Paul Johnson. Original Perl implementation by Michael'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: JS::Test::Simple
name: JS-Test-Simple
no_index:
  directory:
    - inc
    - t
requires:
  JS: 0.14
  perl: 5.6.0
version: 0.25
