---
abstract: ~
author:
  - 'Idea by Tony Bowden and Paul Johnson. Original Perl implementation by Michael'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: JS::Test::Simple
name: JS-Test-Simple
no_index:
  directory:
    - inc
    - t
requires:
  JS: 0.15
  perl: 5.6.0
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 0.29
